# Generated by Django 6.0.2 on 2026-02-08 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('asset_data', models.JSONField(default=dict, help_text='JSON describing the asset to deploy (name, URI, duration, etc.).')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='deploy_files/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.JSONField(blank=True, default=dict, help_text='Per-player progress tracking, e.g. {"player_id": "success"}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_players', models.ManyToManyField(blank=True, related_name='deploy_tasks', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
