# Generated by Django 5.2.11 on 2026-02-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_mediafile_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='processing_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='ready', max_length=20),
        ),
    ]
