# Generated by Django 4.2.28 on 2026-02-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_add_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
