# Generated by Django 4.2.28 on 2026-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0011_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvconfig',
            name='mosaic_layout',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
