# Generated by Django 4.2.28 on 2026-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_cctvconfig_mosaic_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvcamera',
            name='source_type',
            field=models.CharField(choices=[('rtsp', 'RTSP'), ('web', 'Web Page')], default='rtsp', max_length=10),
        ),
    ]
