# Generated by Django 4.2.28 on 2026-02-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict, help_text='Full /v2/info response.')),
                ('assets_count', models.IntegerField(default=0)),
                ('free_space', models.CharField(blank=True, default='', max_length=50)),
                ('load_avg', models.FloatField(default=0.0)),
                ('is_online', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='players.player')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['player', '-timestamp'], name='players_pla_player__29c86d_idx')],
            },
        ),
    ]
