# Generated by Django 4.2.28 on 2026-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auto_registered',
            field=models.BooleanField(default=False),
        ),
    ]
