# Generated by Django 5.2.11 on 2026-02-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_auto_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_assets_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Cached {asset_id: {name, mimetype}} for playback tracking.'),
        ),
        migrations.AddField(
            model_name='player',
            name='history_tracking_since',
            field=models.DateTimeField(blank=True, help_text='When playback tracking started for this player.', null=True),
        ),
        migrations.CreateModel(
            name='PlaybackLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_id', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=200)),
                ('mimetype', models.CharField(blank=True, default='', max_length=50)),
                ('event', models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_logs', to='players.player')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['player', '-timestamp'], name='players_pla_player__e39d59_idx'), models.Index(fields=['-timestamp'], name='players_pla_timesta_bf4e2d_idx')],
            },
        ),
    ]
