# Generated by Django 5.2.11 on 2026-02-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playback_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_viewlog_fetch',
            field=models.CharField(blank=True, default='', help_text='ISO timestamp of last fetched viewlog entry from player.', max_length=50),
        ),
        migrations.AlterField(
            model_name='playbacklog',
            name='event',
            field=models.CharField(choices=[('started', 'Started'), ('stopped', 'Stopped')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='playbacklog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
