# Generated by Django 5.2.11 on 2026-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_viewlog_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='url',
            field=models.URLField(help_text="The player's base URL, e.g. http://192.168.1.10", unique=True),
        ),
        migrations.AddConstraint(
            model_name='playbacklog',
            constraint=models.UniqueConstraint(fields=('player', 'asset_id', 'timestamp', 'event'), name='unique_playback_entry'),
        ),
    ]
