# Generated by Django 4.2.28 on 2026-02-16 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_url_unique_playback_dedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('ssh_user', models.CharField(default='pi', max_length=100)),
                ('ssh_port', models.IntegerField(default=22)),
                ('player_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=11)),
                ('steps', models.JSONField(default=list)),
                ('error_message', models.CharField(blank=True, default='', max_length=1000)),
                ('log_output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provision_tasks', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
