# Generated by Django 4.2.28 on 2026-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_provisiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tailscale_enabled',
            field=models.BooleanField(default=False, help_text='Whether to use Tailscale as fallback for connectivity.'),
        ),
        migrations.AddField(
            model_name='player',
            name='tailscale_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Tailscale VPN IP address (100.x.x.x).', null=True),
        ),
        migrations.AlterField(
            model_name='provisiontask',
            name='total_steps',
            field=models.IntegerField(default=12),
        ),
    ]
